#ifndef RUN_CONFIG_CUH
#define RUN_CONFIG_CUH

#define VERTEX_COUNT 17
#define SUBGRAPH_VERTEX_COUNT 4
#define SEARCH_SYMMETRIC_SOLUTIONS false

#define SECONDS_BETWEEN_SOLUTION_CHECKS 1

#endif //RUN_CONFIG_CUH
